name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build (no-op)
        run: |
          echo "No build step defined; deploying repo root"

      - name: Upload artifact for GitHub Pages
        # use v3 which avoids internal dependency on deprecated actions/upload-artifact@v3
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      # reference the step id below (no hyphens in step ids)
      url: ${{ steps.deploy_pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy_pages
        # use the latest stable deploy-pages action (v3) to avoid deprecation issues
        uses: actions/deploy-pages@v3
